### ISSUE TITLE
Missing quotes for release notes parameter

### ISSUE THREAD

**Issue by Fogh** [ThePerfectApp/fastlane-plugin-tpa#13]
Quotes are missing for the `notes` parameter which requires the quotes to be added as part of the string.

https://github.com/ThePerfectApp/fastlane-plugin-tpa/blob/ae9543823a213953c261154d2eef2a5f7fac4720/lib/fastlane/plugin/tpa/actions/tpa_action.rb#L39

**Comment by mbogh** [comment]
Could you create a PR?

**Comment by bjarkehs** [comment]
#19 Closed this. But since it wasn't referenced in the PR, this issue is not closed.

Feel free to close this.

**Comment by Fogh** [comment]
Closing! Fixed by #19
