### ISSUE TITLE
Add TravisCI, CircleCI or similar to run tests etc?

### ISSUE THREAD

**Issue by mbogh** [ThePerfectApp/fastlane-plugin-tpa#20]
Since this gem actually have tests 😱 , would it not be nice if they were actually run upon new MRs etc?

If we take a look at the [versioning](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/) plugin for fastlane the [.travis.yml](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning/blob/master/.travis.yml) is pretty basic.

It would also mean a badge more for the README 🚀

**Comment by pdrtrifork** [comment]
I added the repo to Travis CI, but it looks like it was actually already there: https://travis-ci.org/ThePerfectApp/fastlane-plugin-tpa.
